
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import { useEffect } from "react";
import {
  useUser,
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { isSignedIn, user } = useUser();
//   // const [appUser, setAppUser] = useState(null);
//   // useEffect(()=>{
  if(isSignedIn && user){
    console.log(user.id);
    // setAppUser(data.user)
  }
// // },[user,isSignedIn])
  return (
    <ClerkProvider>
    <html lang="en">
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      ><SignedOut>
      <SignInButton/>
      <SignUpButton/>
    </SignedOut>
    <SignedIn>
        <UserButton/>
        {children}
        </SignedIn>
      </body>
      
    </html>
    </ClerkProvider>
  );
}
